const variableList = {
  en: [
    "Name",
    "Date",
    "Course Name",
    "Completion Date",
    "Instructor Name",
    "Subject Name",
    "Subject Grade",
    "Parent Name",
    "Sr. No.",
    "Total Marks",
    "Marks Obtained",
    "Approved By",
  ],
  es: [
    "Nombre",
    "Fecha",
    "Nombre del curso",
    "Fecha de Terminación",
    "Nombre del Instructor",
    "Nombre del tema",
    "Calificación de la materia",
    "Nombre del padre",
    "No Señor.",
    "Notas totales",
    "Marcas obtenidas",
    "Aprobado por",
  ],
  ar: [
    "اسم",
    "تاريخ",
    "اسم الدورة التدريبية",
    "موعد الإكمال",
    "اسم المدرب",
    "اسم الموضوع",
    "درجة الموضوع",
    "اسم الوالدين",
    "الأب رقم.",
    "مجموع علامات",
    "العلامات المتحصل عليها",
    "تمت الموافقة عليه من قبل",
  ],
};

export default variableList;
